language: php

php:
  - 5.5

before_script:
  - composer install

script: phpunit --configuration app/phpunit.xml.dist --coverage-text

notifications:
  slack: vektorweb:KvOMl9ysaFBW53wJV3Eu56sS
  email: false
